"""Dual-mode executor for scripted and visual test execution."""

from __future__ import annotations

import re
import time
from typing import Any

from src.core.interfaces import AutomationDriver
from src.core.types import TestStep
from src.journal.models import ActionRecord, ExecutionMode, JournalActionResult
from src.monitoring.logger import get_logger

logger = get_logger(__name__)


class DualModeExecutor:
    """Execute steps using scripted commands first, then visual fallback."""

    def __init__(
        self,
        automation_driver: AutomationDriver,
        visual_executor: Any = None,
    ) -> None:
        self.automation_driver = automation_driver
        self.visual_executor = visual_executor
        self.stats = {
            "scripted_attempts": 0,
            "scripted_successes": 0,
            "visual_fallbacks": 0,
            "total_time_saved_ms": 0,
        }

    async def execute_action(
        self,
        step: TestStep,
        pattern: ActionRecord | None = None,
        context: dict[str, Any] | None = None,
    ) -> tuple[JournalActionResult, ExecutionMode, int]:
        del context
        started = time.time()

        if pattern and pattern.automation_command:
            self.stats["scripted_attempts"] += 1
            scripted_ok = await self._try_scripted_execution(pattern.automation_command)
            if scripted_ok:
                elapsed = int((time.time() - started) * 1000)
                self.stats["scripted_successes"] += 1
                self.stats["total_time_saved_ms"] += max(0, 2000 - elapsed)
                return (
                    JournalActionResult(
                        success=True,
                        action=step.action_instruction.action_type
                        if step.action_instruction
                        else None,
                        confidence=1.0,
                        automation_command=pattern.automation_command,
                    ),
                    ExecutionMode.SCRIPTED,
                    elapsed,
                )

            self.stats["visual_fallbacks"] += 1

        if self.visual_executor is None:
            elapsed = int((time.time() - started) * 1000)
            return (
                JournalActionResult(
                    success=False,
                    confidence=0.0,
                    error_message="No visual executor available for fallback",
                ),
                ExecutionMode.VISUAL,
                elapsed,
            )

        screenshot = await self.automation_driver.screenshot()
        if not step.action_instruction:
            elapsed = int((time.time() - started) * 1000)
            return (
                JournalActionResult(
                    success=False,
                    confidence=0.0,
                    error_message="Step is missing action instruction",
                ),
                ExecutionMode.VISUAL,
                elapsed,
            )

        result = await self.visual_executor.determine_action(
            screenshot=screenshot,
            instruction=step.action_instruction,
        )
        elapsed = int((time.time() - started) * 1000)
        return (
            JournalActionResult(
                success=True if result else False,
                action=step.action_instruction.action_type,
                confidence=getattr(result.coordinate, "confidence", 0.0)
                if result
                else 0.0,
            ),
            ExecutionMode.VISUAL,
            elapsed,
        )

    async def _try_scripted_execution(self, command: str) -> bool:
        """Execute a single automation command string."""
        normalized = (command or "").strip()
        if not normalized:
            return False

        # Support compound command strings generated by fallback scripts.
        parts = [part.strip() for part in normalized.split(";") if part.strip()]
        if len(parts) > 1:
            for part in parts:
                if not await self._try_scripted_execution(part):
                    return False
            return True

        if " " in normalized:
            action, raw_args = normalized.split(" ", 1)
        else:
            action, raw_args = normalized, ""
        action = action.strip().lower()
        args = self._parse_key_value_args(raw_args)

        if action == "wait":
            milliseconds = self._to_int(
                args.get("ms") or args.get("milliseconds") or "0"
            )
            if milliseconds <= 0:
                return False
            await self.automation_driver.wait(milliseconds)
            return True

        if action == "navigate":
            url = (args.get("url") or "").strip()
            if not url:
                return False
            await self.automation_driver.navigate(url)
            return True

        if action == "type":
            text = args.get("text")
            if text is None:
                return False
            await self.automation_driver.type_text(text)
            return True

        if action == "click":
            x = self._to_int(args.get("x"))
            y = self._to_int(args.get("y"))
            if x is None or y is None:
                # Selector-only click commands are not executable in desktop mode.
                return False
            await self.automation_driver.click(x, y)
            return True

        if action == "scroll":
            direction = (args.get("direction") or "down").lower()
            amount = self._to_int(args.get("amount"))
            if amount is None:
                return False
            await self.automation_driver.scroll(direction, amount)
            return True

        if action == "keypress":
            key = (args.get("key") or "").strip()
            if not key:
                return False
            await self.automation_driver.press_key(key)
            return True

        if action == "screenshot":
            await self.automation_driver.screenshot()
            return True

        return False

    @staticmethod
    def _parse_key_value_args(raw_args: str) -> dict[str, str]:
        """Parse command args formatted as `key=value` pairs."""
        parsed: dict[str, str] = {}
        for key, value in re.findall(
            r"(\w+)=('(?:[^'\\]|\\.)*'|\"(?:[^\"\\]|\\.)*\"|[^\s]+)", raw_args or ""
        ):
            normalized = value.strip()
            if (
                len(normalized) >= 2
                and normalized[0] == normalized[-1]
                and normalized[0] in {"'", '"'}
            ):
                normalized = normalized[1:-1]
            parsed[key] = normalized
        return parsed

    @staticmethod
    def _to_int(value: str | None) -> int | None:
        """Convert a string value to int when possible."""
        if value is None:
            return None
        try:
            return int(value)
        except (TypeError, ValueError):
            return None

    def get_stats(self) -> dict[str, Any]:
        """Get execution statistics."""
        attempts = self.stats["scripted_attempts"]
        successes = self.stats["scripted_successes"]
        return {
            **self.stats,
            "scripted_success_rate": (successes / attempts) if attempts else 0.0,
        }

    def reset_stats(self) -> None:
        """Reset execution statistics."""
        self.stats = {
            "scripted_attempts": 0,
            "scripted_successes": 0,
            "visual_fallbacks": 0,
            "total_time_saved_ms": 0,
        }
